### ISSUE TITLE
Does not work in Python 3.x

### ISSUE THREAD

**Issue by natskvi** [cadithealth/passwordmeter#1]
import passwordmeter
File "C:\Python34\lib\site-packages\passwordmeter__init__.py", line 23, in <module>
common10k = frozenset(asset.load('passwordmeter:res/common.txt').read().split('\n'))
TypeError: 'str' does not support the buffer interface

**Comment by grabner** [comment]
fixed in 0.1.7.

that said, i don't use python 3 very much, so i can't guarantee that there won't be other issues... (it does pass all of my unit tests though). so, if you _do_ find more issues, i apologize in advance -- please let me know and i will fix them.

**Comment by natskvi** [comment]
Wow, talk about fast turnaround!  :)  Thank you very much.

Regards,

Nathan

**Comment by natskvi** [comment]
Hi Philip,

Last question: Is a new pip installer package created upon a commit to Git or does it require you to create it manually?

Thank you,

Nathan

**Comment by grabner** [comment]
i uploaded the latest package to pypi, so a `pip install --upgrade passwordmeter` should get you 0.1.7 (the --upgrade is only needed if you already had it installed).

**Comment by natskvi** [comment]
Perfect, exactly the information I needed.  Thank you very much, once again.

Regards,

Nathan
